name: micro_news
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.5.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  google_sign_in: ^4.0.4
  firebase_storage: ^3.0.4
  image_picker: ^0.6.1
  font_awesome_flutter: ^8.5.0
  path_provider: ^1.1.0
  flutter_staggered_grid_view: ^0.3.0
  cloud_firestore: ^0.13.5
  firebase_helpers: ^0.1.0
  carousel_pro: ^0.0.13
  transparent_image: ^1.0.0
  scoped_model: ^1.0.1
  firebase_auth: ^0.11.1
  url_launcher: ^5.0.2
  flutter_datetime_picker: ^1.3.8
  datetime_picker_formfield: ^1.0.0
  intl: ^0.16.0
  intl_translation: ^0.17.7
  english_words: 3.1.5
  timeline: 0.0.1
  webview_flutter: ^0.3.14+1
  flutter_launcher_icons: ^0.7.4
  shared_preferences: ^0.5.6+3
  localstorage: ^3.0.1+4
  splashscreen: ^1.2.0
  random_string: ^2.0.1
  provider: ^2.0.1+1
  rxdart: ^0.22.0
  table_calendar: ^2.0.1
  mask_text_input_formatter: ^1.0.6
  android_alarm_manager: ^0.4.1+6
  flutter_sparkline: ^0.1.0
  flutter_circular_chart: ^0.1.0
  bezier_chart: ^1.0.17+1
  flutter_local_notifications:
  flare_flutter:
    git:
      url: git://github.com/2d-inc/Flare-Flutter.git
      ref: dev
      path: flare_flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

#flutter_icons:
#  android: "launcher_icon"
#  ios: true
#  image_path: "assets/images/114.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
    - assets/sound/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Ic
      fonts:
        - asset: assets/fonts/ic/ic_medicine.ttf
    - family: Angel
      fonts:
        - asset: assets/fonts/neu/Angel Signature.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
